```{r library, include=FALSE}
my_packages <- c("tidyverse", "data.table", "readxl",
                 "plyr",
                 "ggvenn", "ggpubr")
pacman::p_load(char = my_packages)

tmp <- list()
```

# load data
```{r}
load("Output/Steps/R01/ccle_drug_leu_v1.Rda")
load("Output/Steps/R01/gdsc_drug_leu_v1.Rda")
load("Output/Steps/R01/beatAML_drug_leu_v1.Rda")
load("Output/Steps/R01/gCSI_drug_leu_v1.Rda")
load("Output/Steps/R01/tavor_drug_leu_v1.Rda")
load("Output/Steps/R01/FORALL_drug_leu_v1.Rda")
# load("Output/Steps/R01/")
```

# Check overlaps
drugs:
```{r}
# ggvenn::ggvenn(
#   list(
#     gdsc1 = colnames(gdsc1_drug_leu)[-1],
#     gdsc2 = colnames(gdsc2_drug_leu)[-1],
#     ctrp1 = colnames(ctrp1_drug_leu)[-1],
#     ctrp2 = colnames(ctrp2_drug_leu)[-1]
#   )
# )
```

```{r}
# ggvenn::ggvenn(
#   list(
#     gdsc1 = gdsc1_drug_leu$COSMIC_ID,
#     gdsc2 = gdsc2_drug_leu$COSMIC_ID,
#     ctrp1 = ctrp1_drug_leu$DepMap_ID,
#     ctrp2 = ctrp2_drug_leu$DepMap_ID
#   )
# )
```

# Total statistics
## Counts
```{r}
all_stat <- data.frame(
  counts = c(dim(ctrp1_drug_leu),
             dim(ctrp2_drug_leu),
             dim(gdsc1_drug_leu),
             dim(gdsc2_drug_leu),
             dim(beatAML_drug_leu),
             dim(FORALL_drug_leu),
             dim(tavor_drug_leu)),
  source = rep(c("CTRP1", "CTRP2", 
                 "GDSC1", "GDSC2",
                 "beatAML", "FORALL", "tavor"),
               each = 2),
  type = rep(c("Cells", "Drugs"), times = 7)
)
```

```{r}
p_count_drugandcell <- ggplot(all_stat, aes(x = source, 
                     y = counts,
                     fill = type)) + geom_col(position = "dodge") + geom_text(aes(label = counts), position = position_dodge(0.9), vjust = -0.8) + theme_bw() + theme(
                       axis.title.x = element_blank()
                     ) + coord_cartesian(ylim = c(0, 600))
# + scale_fill_manual(values = paletteer::paletteer_d("RColorBrewer::Set3")[3:4])
p_count_drugandcell
```

## Cell type counts 
```{r}
ctrp1_anno <- ccle_anno_leu[ccle_anno_leu$stripped_cell_line_name %in% ctrp1_drug_leu$cell,]
tmp$ctrp1 <- ctrp1_anno %>% group_by(lineage_subtype) %>%
  dplyr::summarise(count = n())
tmp$ctrp1$source <- "CTRP1"
  
ctrp2_anno <- ccle_anno_leu[ccle_anno_leu$stripped_cell_line_name %in% ctrp2_drug_leu$cell,]
tmp$ctrp2 <- ctrp2_anno %>% group_by(lineage_subtype) %>%
  dplyr::summarise(count = n())
tmp$ctrp2$source <- "CTRP2"

gdsc1_anno <- gdsc_anno_leu[gdsc_anno_leu$Name2 %in% gdsc1_drug_leu$cell,]
tmp$gdsc1 <- gdsc1_anno %>% group_by(lineage_subtype) %>%
  dplyr::summarise(count = n())
tmp$gdsc1$source <- "GDSC1"

gdsc2_anno <- gdsc_anno_leu[gdsc_anno_leu$Name2 %in% gdsc2_drug_leu$cell,]
tmp$gdsc2 <- gdsc2_anno %>% group_by(lineage_subtype) %>%
  dplyr::summarise(count = n())
tmp$gdsc2$source <- "GDSC2"

tmp$beatAML <- data.frame(
  lineage_subtype = "AML",
  count = 528,
  source = "beatAML"
)

tmp$tavor <- data.frame(
  lineage_subtype = c("AML", "APL"),
  count = c(46, 4),
  source = "tavor"
)

tmp$FORALL <- data.frame(
  lineage_subtype = c("ALL"),
  count = c(43),
  source = "FORALL"
)
```

```{r}
all_stat_subtype <- rbind(tmp$ctrp1,
                          tmp$ctrp2,
                          tmp$gdsc1,
                          tmp$gdsc2,
                          tmp$beatAML,
                          tmp$tavor,
                          tmp$FORALL)
```

```{r}
p_count_subtype <- ggplot(all_stat_subtype, aes(x = source, 
                     y = count,
                     fill = lineage_subtype)) + geom_col(position = position_dodge2(preserve = "single")) + geom_text(aes(label = count), position = position_dodge2(width = 0.9, preserve = "single"), vjust = -0.8) + theme_bw() + theme(
                       axis.title.x = element_blank()
                     )  + 
  scale_fill_manual(values = rev(paletteer::paletteer_d("RColorBrewer::Set3"))
                       ) + 
  coord_cartesian(ylim = c(0, 600))
p_count_subtype
```

```{r}
p_count_subtype <- p_count_subtype + ggtitle("Subtype Cell Counts") + theme(legend.position = "top")
p_count_subtype
```

```{r}
p_count_drugandcell <- p_count_drugandcell + ggtitle("Drugs and Cells Total Counts") + theme(legend.position = "top")
p_count_drugandcell
```

# Anno Info
## Cell
```{r}
gdsc_anno <- gdsc_anno_leu
ccle_anno <- ccle_anno_leu

gdsc_anno <- gdsc_anno[,c(1,2,6,7)]
colnames(gdsc_anno) <- c("CellName", "Barcode", "Lineage_subtype", "Lineage_sub_subtype")

ccle_anno <- ccle_anno[,c(2,1,6,7)]
colnames(ccle_anno) <- c("CellName", "Barcode", "Lineage_subtype", "Lineage_sub_subtype")

beatAML_anno <- beatAML_anno_leu[beatAML_anno_leu$sampleid %in% beatAML_drug_leu$cell,]
beatAML_anno <- beatAML_anno[,1:87]

FORALL_anno <- read_xlsx("Input/Datasets/FORALL/cellanno.xlsx", sheet = 2)
FORALL_anno <- FORALL_anno[FORALL_anno$`Cell Line Name` %in% FORALL_drug_leu$cells,]

tavor_anno <- tavor_anno_leu 

gCSI_anno <- gCSI_anno_leu[,c(1,2,6,7)]
```

Collect key info:
```{r}
FORALL_anno2 <- FORALL_anno[,c(1,7,9)]
tavor_anno2 <- tavor_anno[,c(1,7)]
tavor_anno2$Lineage <- ifelse(
  grepl("APL", tavor_anno2$Diagnosis),
  "APL", "AML"
)
```

## Drugs
```{r}
load("Output/Steps/R01/gdsc_drug_anno_v2.Rda")
# load(file = "Output/Steps/R03/shiny/leu_drugs_sd.Rda")

drug_anno <- fread("Input/Datasets/Drug/Repurposing_Hub_export.txt")
```

```{r}
gdsc_drug_anno <- merge(gdsc_drug_anno, gdsc_drug_rename,
                        by.x = "DRUG_NAME2", by.y = "new")
tmp$rep_names <- gdsc_drug_anno[duplicated(gdsc_drug_anno$DRUG_NAME2),]$DRUG_NAME2

gdsc_drug_anno[gdsc_drug_anno$DRUG_NAME2 %in% tmp$rep_names,]
```

remove duplicated drugs:
```{r}
gdsc_drug_anno[62,]$TARGET_PATHWAY <- "RTK/IGF1R signaling"
gdsc_drug_anno[149,]$TARGET_PATHWAY <- "RTK/IGF1R signaling"
gdsc_drug_anno[197,]$TARGET_PATHWAY <- "RTK/EGFR signaling"

gdsc_drug_anno <- gdsc_drug_anno[-c(40,59,63,108,150,198,233,325),]
```


```{r}
gdsc1_drug_anno <- gdsc_drug_anno[gdsc_drug_anno$old %in% colnames(gdsc1_drug_leu)[-1],][,c(3,2)]
colnames(gdsc1_drug_anno)[1] <- "drugs"
gdsc2_drug_anno <- gdsc_drug_anno[gdsc_drug_anno$old %in% colnames(gdsc2_drug_leu)[-1],][,c(3,2)]
colnames(gdsc2_drug_anno)[1] <- "drugs"

ctrp1_drug_anno <- data.frame(drugs = colnames(ctrp1_drug_leu)[-1])
ctrp1_drug_anno <- merge(ctrp1_drug_anno,
                         drug_anno[,c(1:2)], by.x = "drugs", by.y = "Name", all.x = T)
ctrp2_drug_anno <- data.frame(drugs = colnames(ctrp2_drug_leu)[-1])
ctrp2_drug_anno <- merge(ctrp2_drug_anno,
                         drug_anno[,c(1:2)], by.x = "drugs", by.y = "Name",
                         all.x = T)

beatAML_drug_anno <- data.frame(drugs = colnames(beatAML_drug_leu)[-1])
beatAML_drug_anno <- merge(beatAML_drug_anno,
                         drug_anno[,c(1:2)], by.x = "drugs", by.y = "Name",
                         all.x = T)

tavor_drug_anno <- data.frame(drugs = colnames(tavor_drug_leu)[-1])
tavor_drug_anno <- merge(tavor_drug_anno,
                         drug_anno[,c(1:2)], by.x = "drugs", by.y = "Name",
                         all.x = T)

gCSI_drug_anno <- data.frame(drugs = colnames(gCSI_drug_leu)[-1])
gCSI_drug_anno <- merge(gCSI_drug_anno,
                        drug_anno[,c(1:2)], by.x = "drugs", by.y = "Name",
                        all.x = T)

FORALL_drug_anno <- FORALL_druganno_leu[,c(1:2)]
```


# Save
```{r}
save(p_count_subtype,
     p_count_drugandcell,
     file = "Output/Steps/R02/shiny/leu_drugs_stat_plot.Rda")
```

```{r}
save(gdsc_anno,
     ccle_anno,
     beatAML_anno,
     tavor_anno,
     FORALL_anno,
     gCSI_anno,
     file = "Output/Steps/R02/shiny/leu_anno_shiny_all.Rda")

save(gdsc_anno,
     ccle_anno,
     tavor_anno2,
     FORALL_anno2,
     gCSI_anno,
     file = "Output/Steps/R02/shiny/leu_anno_shiny.Rda")
```

```{r}
save(gdsc1_drug_anno,
     gdsc2_drug_anno,
     ctrp1_drug_anno,
     ctrp2_drug_anno, 
     beatAML_drug_anno,
     tavor_drug_anno,
     gCSI_drug_anno,
     FORALL_drug_anno,
     file = "Output/Steps/R02/shiny/leu_drug_anno_shiny.Rda")
```

